FROM nginx:latest
WORKDIR /usr/share/nginx/html

RUN rm -rf ./* && rm /etc/nginx/conf.d/default.conf
RUN mkdir /etc/nginx/ssl && chmod 700 /etc/nginx/ssl

COPY dist/ .
COPY nginx/nginx.conf /etc/nginx

COPY nginx/load_config.sh /app/load_config.sh
RUN ["chmod", "+x", "/app/load_config.sh"]

ENTRYPOINT ["/bin/sh", "-c", "/app/load_config.sh"]